ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS display_name VARCHAR(150),
ADD COLUMN IF NOT EXISTS profession VARCHAR(255),
ADD COLUMN IF NOT EXISTS country_code CHAR(2),
ADD COLUMN IF NOT EXISTS state VARCHAR(150),
ADD COLUMN IF NOT EXISTS city VARCHAR(150);
